import { workflowMarkup } from './trust-ui.js';
import { escape as esc, number as num } from './api.js';

const paths = {
  plus:'M12 5v14M5 12h14', search:'m21 21-4.3-4.3M19 10.5a8.5 8.5 0 1 1-17 0 8.5 8.5 0 0 1 17 0',
  folder:'M3 7V5h6l2 2h10v13H3Z', panel:'M3 4h18v16H3ZM9 4v16',
  arrow:'M12 19V5m-6 6 6-6 6 6', chevron:'m9 5 7 7-7 7',
  file:'M14 2H5v20h14V7ZM14 2v6h5M8 13h8M8 17h6',
  run:'m8 4 12 8-12 8Z', check:'m5 12 4 4L19 6',
  layers:'m12 3 10 5-10 5L2 8Zm-10 9 10 5 10-5M2 16l10 5 10-5',
  moon:'M20 14A9 9 0 0 1 10 4a9 9 0 1 0 10 10',
  exit:'M9 3H4v18h5M10 12h11m-4-4 4 4-4 4',
  dots:'M5 12h.01M12 12h.01M19 12h.01', bolt:'m13 2-9 12h7l-1 8 10-12h-7Z',
};
export const icon = (name) => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+(paths[name] || paths.file)+'"/></svg>';
export const mark = '<span class="brandmark">'+icon('layers')+'</span>';

export function appShell(state) {
  const p = state.project;
  return `<div class="app-frame"><aside class="app-sidebar"><a class="brand" href="/">${mark}<span>稀土智暖 <small>VRA-Trust</small></span></a>
    <button class="nav-action" id="new-project">${icon('plus')}<span>新建项目</span><kbd>⌘ N</kbd></button>
    <button class="nav-action" id="search-projects">${icon('search')}<span>搜索项目</span><kbd>⌘ K</kbd></button>
    <button class="nav-action ${!p?'active':''}" id="all-projects">${icon('panel')}<span>工作台</span></button>
    <div class="sidebar-label">项目 <span>${state.projects.length}</span></div><div class="sidebar-projects">${state.projects.map(item=>`<button class="sidebar-project ${item.project_id===p?.project_id?'active':''}" data-project="${item.project_id}" title="${esc(item.name)}">${icon('folder')}<span>${esc(item.name)}</span>${item.data_nature==='engineering_reference'?'<i>示例</i>':''}</button>`).join('')||'<p class="sidebar-empty">你的项目会显示在这里</p>'}</div>
    <button class="nav-action subtle-action" id="load-reference">${icon('layers')}<span>探索参考项目</span></button>
    ${state.user.is_admin?'<button class="nav-action" id="developer-settings">'+icon('dots')+'<span>开发者设置</span></button>':''}<div class="account-row"><span class="avatar">${esc(state.user.display_name.slice(0,1))}</span><span class="account-name">${esc(state.user.display_name)}<small>本地工作区</small></span><button class="icon-button" id="theme-toggle" aria-label="切换明暗主题">${icon('moon')}</button><button class="icon-button" id="logout" aria-label="退出登录">${icon('exit')}</button></div></aside>
    <div class="app-body"><header class="topbar"><button id="toggle-sidebar" class="icon-button" aria-label="展开或收起侧栏">${icon('panel')}</button><div class="breadcrumb">${p?`<span>项目</span><span class="slash">/</span><strong>${esc(p.name)}</strong>`:'<strong>工作台</strong>'}</div><div class="topbar-end"><span class="engine-indicator"><i class="${state.health?.engine_available?'online':''}"></i>${state.health?.engine_available?'引擎就绪':'引擎未连接'}</span>${p?'<button id="toggle-inspector" class="icon-button" aria-label="查看项目详情">'+icon('file')+'</button>':''}</div></header><div id="workspace"></div></div></div><div id="toast" class="toast" role="status" hidden></div><dialog id="dialog"></dialog>`;
}

export function homeView(state) {
  return `<main class="home"><div class="home-intro"><span class="home-emblem">${icon('layers')}</span><p class="greeting">建筑节能改造工作区</p><h1>今天，想推进哪个项目？</h1><p class="home-subtitle">整理资料、运行仿真，让每个判断都有依据。</p></div>
  <form class="composer home-composer" id="intake-composer"><label class="sr-only" for="project-intent">项目名称或描述</label><textarea id="project-intent" placeholder="为你的建筑项目起个名字…" maxlength="160" rows="2"></textarea><div class="composer-bottom"><button type="button" class="composer-tool" id="create-project">${icon('plus')} 创建项目</button><span class="composer-hint">从项目资料开始</span><button class="send-button" type="submit" aria-label="创建这个项目">${icon('arrow')}</button></div></form>
  <div class="starter-actions"><button id="reference-project">${icon('layers')}体验官方参考项目</button><button id="how-it-works">${icon('file')}了解工作流程</button></div>
  ${workflowMarkup()}<section class="recent"><div class="section-title"><h2>最近项目</h2><span>${state.projects.length?'继续上次的工作':'还没有项目'}</span></div>${state.projects.slice(0,5).map(p=>`<button class="recent-project" data-project="${p.project_id}"><span class="recent-icon">${icon('folder')}</span><span><strong>${esc(p.name)}</strong><small>${esc(p.building.location)} · ${num(p.building.area_m2)} m²${p.data_nature==='engineering_reference'?' · 官方参考，非实测':''}</small></span>${icon('chevron')}</button>`).join('')||'<div class="home-empty">创建第一个项目后，可导入图纸、台账、IDF 模型和天气文件。</div>'}</section><p class="home-footnote">有依据的计算，有边界的建议。</p></main>`;
}

export function projectView(state) {
  const p=state.project, ready=state.gate.can_simulate, pending=state.evidence.filter(e=>e.review_state==='pending').length;
  return `<div class="project-workspace"><div class="workspace-main"><nav class="view-tabs" aria-label="项目工作视图">${[['readiness','工作台'],['evidence','资料'],['simulation','仿真'],['trace','报告与依据'],['robustness','反例与补证'],['spatial','图纸与三维']].map(([id,label])=>`<button data-view="${id}" class="${state.view===id?'selected':''}">${label}${id==='evidence'?'<span>'+state.evidence.length+'</span>':''}</button>`).join('')}</nav>
  <section class="work-view task-view" id="readiness"><div class="task-thread"><div class="task-title"><span class="eyebrow">${p.data_nature==='engineering_reference'?'官方参考 · 非实测':'工程项目'}</span><h1>${ready?'资料已就绪，可以开始计算。':'先把建筑资料准备好。'}</h1><p>${ready?'模型与天气已确认。运行后可以查看每个结果的原始依据。':'导入模型和天气文件，确认来源后再运行仿真。'}</p></div>
  <div class="assistant-message"><span class="message-mark">${icon('layers')}</span><div><strong>项目状态</strong><p>已登记 ${state.evidence.length} 份资料${pending?'，其中 '+pending+' 份等待人工确认':''}。</p>${state.gate.blockers.length?'<ul class="gap-list">'+state.gate.blockers.map(b=>'<li><strong>'+esc(b.message)+'</strong><span>'+esc(b.action)+'</span></li>').join(''):'<p class="inline-status">'+icon('check')+'关键输入通过准入检查</p>'}<div class="message-actions"><button id="task-import">${icon('plus')}导入资料</button><button id="task-next">${icon(ready?'run':'check')}${ready?'前往仿真':'查看并确认资料'}</button></div></div></div>
  <div id="task-response" aria-live="polite"></div><div class="decision-note">${icon('file')}<span>当前尚不能给出确定推荐。舒适性、模型适用性和方案稳定性仍需复核。</span></div></div>
  <form class="composer task-composer" id="task-command"><label class="sr-only" for="command">项目操作</label><textarea id="command" rows="2" placeholder="询问依据、资料缺口或仿真准入；AI Provider 需先配置 Key…"></textarea><div class="composer-bottom"><button type="button" class="composer-tool" id="composer-upload">${icon('plus')}资料</button><select id="agent-mode" aria-label="执行模式"><option value="local">本地工程流程</option><option value="provider">AI Provider</option></select><label class="compute-opt"><input type="checkbox" id="allow-compute">允许计算</label><button class="send-button" type="submit" aria-label="执行项目操作">${icon('arrow')}</button></div></form></section>
  <section class="work-view" id="evidence" hidden><div class="view-heading"><div><h1>项目资料</h1><p>保留原文件与来源，确认后进入计算流程。</p></div><button class="primary" id="add-evidence">${icon('plus')}导入资料</button></div><div id="evidence-table"></div><div class="section-footer"><button id="review-pending">${icon('check')}确认待审模型与天气</button><span>确认操作会保留复核人和版本记录。</span></div></section>
  <section class="work-view" id="simulation" hidden><div class="view-heading"><div><h1>仿真与方案</h1><p>每次计算独立保存输入、结果和原始输出。</p></div><span id="simulation-health">${state.runs.length?'见运行记录':'未计算'}</span></div><div class="run-controls"><label>方案<select id="scheme"><option value="baseline">baseline · 基准</option><option value="R1">R1 · 候选方案</option><option value="R2">R2 · 候选方案</option></select></label><label>运行碳因子<select id="factor">${Object.keys(state.profiles).map(key=>`<option value="${esc(key)}">${esc(key==='none'?'暂不计算碳排':key==='reference_scenario'?'教学情景 · 非正式核算':key)}</option>`).join('')}</select></label><button id="run" class="primary">${icon('run')}运行仿真</button><button id="compare">比较最近三方案</button><button id="edit-factors">修改碳因子</button></div><div id="runs"></div><div id="comparison"></div></section>
  <section class="work-view" id="trace" hidden><div class="view-heading"><div><h1>报告与依据</h1><p>从结果回到输入，查看来源、版本和成立条件。</p></div></div><div id="trace-content" class="empty">请在仿真记录中选择“查看依据”。</div><p class="subtle">节点依赖、来源版本与选择性重算；报告为未签署草稿。</p></section><section class="work-view" id="robustness" hidden></section><section class="work-view" id="spatial" hidden></section></div>
  <aside class="inspector" hidden><div class="inspector-heading">项目详情<button id="close-inspector" class="icon-button" aria-label="关闭项目详情">×</button></div><div class="inspector-section"><span class="eyebrow">建筑</span><h3>${esc(p.building.use)}</h3><dl><dt>地点</dt><dd>${esc(p.building.location)}</dd><dt>建筑面积</dt><dd>${num(p.building.area_m2)} m²</dd><dt>声明版本</dt><dd>v${p.revision}</dd></dl><button id="edit-building">编辑建筑资料</button></div><div class="inspector-section"><span class="eyebrow">决策状态</span><dl><dt>仿真准入</dt><dd>${ready?'已满足':'待补齐'}</dd><dt>稳定性</dt><dd>未评估</dd><dt>工程师签署</dt><dd>未签署</dd></dl></div><div class="inspector-section"><span class="eyebrow">证据索引</span>${state.evidence.map(e=>`<button class="inspector-file" data-evidence="${e.evidence_id}">${icon('file')}<span>${esc(e.name)}<small>${e.review_state==='confirmed'?'已确认':'待复核'} · v${e.revision}</small></span></button>`).join('')||'<p class="subtle">尚未导入资料</p>'}</div></aside></div>`;
}

export function authView({setup=false, register=false}) {
  return `<div class="auth-page"><a class="brand auth-brand" href="/">${mark}<span>稀土智暖 <small>VRA-Trust</small></span></a><main class="auth-main"><div class="auth-heading"><span class="auth-emblem">${icon('layers')}</span><h1>${setup?'创建你的工作区':register?'创建账号':'欢迎回来'}</h1><p>${setup?'从一个账号开始，管理你的项目与工程证据。':register?'建立自己的建筑改造项目空间。':'登录，继续你的建筑改造项目。'}</p></div><form id="auth-form">${register||setup?'<label>怎么称呼你<input name="display_name" autocomplete="name" required maxlength="40" placeholder="你的名字"></label>':''}<label>用户名<input name="username" autocomplete="username" required minlength="3" maxlength="32" pattern="[A-Za-z0-9_\\-]{3,32}" placeholder="字母、数字、下划线，3–32 位"></label><label>密码<div class="password-field"><input id="password" name="password" type="password" autocomplete="${register||setup?'new-password':'current-password'}" required minlength="10" maxlength="128" placeholder="至少 10 个字符"><button id="show-password" type="button" aria-label="显示密码">显示</button></div></label><p id="auth-error" role="alert" hidden></p><button type="submit" class="primary auth-submit">${setup?'创建工作区':register?'创建账号':'登录'}${icon('chevron')}</button></form>${setup?'<p class="auth-note">已有本机项目会归入这个首个账号。请妥善保存密码，当前不支持邮件找回。</p>':'<p class="auth-switch">'+(register?'已有账号？':'还没有账号？')+'<button id="switch-auth">'+(register?'登录':'创建账号')+'</button></p>'}<div class="auth-divider"></div><p class="auth-local">账号与项目保存在本机 · 密码不以明文保存</p></main><footer class="auth-footer">可复核 · 可拒答 · 可补证 · 可重放</footer></div><div id="toast" class="toast" role="status" hidden></div>`;
}
