import {request,post,escape as esc,number as num} from './api.js';
import {createPoller} from './polling.js';
export async function robustnessWorkspace(state,host,action) {
  const pid=state.project.project_id,base='/projects/'+pid;
  const catalog=await request(base+'/search-materials');
  if(!host.isConnected)return;
  const evidence=state.evidence.filter(e=>e.review_state==='confirmed'&&!['MISSING','AI_INFERRED'].includes(e.status));
  const actionPlans=new Map();
  const stabilityLabel={COUNTEREXAMPLE_FOUND:'发现方案排序翻转',NO_FLIP_WITHIN_BUDGET:'预算内未发现翻转',STABLE_ON_ENUMERATED_GRID:'声明离散点已遍历，未发现翻转',RANKING_INDETERMINATE:'差异落入容差，排名不确定',SIMULATION_FAILED:'搜索失败，结论不可用',STALE:'输入或算法已变化，结论失效',NOT_ASSESSED:'尚未形成稳定性结论'};
  host.innerHTML=`<div class="view-heading"><div><h1>决策稳健性</h1><p>真实仿真寻找反例。范围限定为共同材料的导热系数离散点，目标为全年场地能耗。</p></div></div><form id="search-form"><div class="form-grid"><label>材料对象<select name="material" required>${catalog.materials.map(m=>`<option value="${esc(m.name)}">${esc(m.name)} · 当前 ${m.conductivity_w_mk.map(v=>num(v,4)).join(' / ')} W/(m·K)</option>`).join('')}</select></label><label>EnergyPlus 最大调用数<input name="budget" type="number" min="${Math.max(2,catalog.run_ids.length)}" max="24" value="6" required></label></div><label>搜索离散值（W/(m·K)，逗号分隔，2–6 个正数）<input name="values" required placeholder="填写有依据的离散点；不自动猜测范围"></label><label>搜索域来源与适用依据<textarea name="source" required minlength="5" placeholder="文献/测量范围/明确标注的教学假设"></textarea></label><label>关联已复核证据（可选）<select name="evidence_id"><option value="">仅使用上方明确声明的搜索域依据</option>${evidence.map(e=>`<option value="${e.evidence_id}">${esc(e.name)} · v${e.revision} · ${esc(e.status)}</option>`).join('')}</select></label><p class="subtle">关联后会冻结证据版本；来源撤回、修订或文件损坏会使该搜索失效。确认操作不改变假设资料的性质。</p><p class="form-note">每个完整点需要 ${catalog.run_ids.length} 次仿真。包括 baseline 且至少两个当前有效方案才能启动。页面使用各方案最新运行，历史成功结果不会替代最新失败结果。</p><button type="submit" class="primary" ${catalog.run_ids.length<2?'disabled':''}>启动有预算的真实搜索</button></form><div id="search-list"></div>`;
  const render=studies=>{host.querySelector('#search-list').innerHTML=studies.map(s=>`<section class="study-result"><h3>${esc(stabilityLabel[s.stability_status]||s.stability_status)}</h3><small class="mono">${esc(s.stability_status)}</small><p>${esc(s.status)} · 已调用 ${s.engine_calls} / ${s.budget} 次 · ${num((s.coverage??0)*100)}% 声明网格覆盖</p><p>${esc(s.stale_reasons?.join('；')||s.error||s.limitation||'正在执行真实仿真，结果尚未成立')}</p><table><thead><tr><th>离散参数</th><th>${s.status==='succeeded'?'能耗排序':'历史或未完成排序'}</th><th>反例</th></tr></thead><tbody>${s.points.map(p=>`<tr><td>${esc(JSON.stringify(p.parameters))}</td><td>${p.order? p.order.map(esc).join(' → '):'未完成'}</td><td>${s.status!=='succeeded'?'当前不可判定':p.flipped===true?'发现翻转':p.flipped===false?'该点未翻转':'—'}</td></tr>`).join('')}</tbody></table>${s.status!=='running'?`<a href="/api${base}/searches/${s.search_id}/artifacts" target="_blank" rel="noopener">下载搜索证据与原始仿真 ZIP ↗</a>`:''}<details><summary>查看范围、run_id 和原始验证索引</summary><pre>${esc(JSON.stringify(s,null,2))}</pre></details>${s.status==='succeeded'?`<form data-actions="${s.search_id}"><h4>补证成本情景</h4><p class="subtle">假设下一次测量确认某个已搜索值，计算可排除的已发现反例数。不把这个条件情景当成实际测量或风险概率。</p><label>假设测量确认的导热系数<input name="confirmed_value" type="number" step="any" required></label><div class="form-grid"><label>费用 CNY<input name="cost_cny" type="number" min="0" required></label><label>耗时 h<input name="duration_hours" type="number" min="0" step=".1" required></label></div><label>获取方式<input name="method" required minlength="3"></label><button type="submit">加入候选并排序</button><div class="action-result"></div></form>`:''}</section>`).join('')||'<p class="empty">尚无反例搜索。未搜索不能声称稳定。</p>';host.querySelectorAll('[data-actions]').forEach(form=>{form.onsubmit=e=>{e.preventDefault();const f=new FormData(form),study=studies.find(s=>s.search_id===form.dataset.actions);action(async()=>{const proposed=[...(actionPlans.get(study.search_id)||[]),{material:study.axes[0].material,confirmed_value:Number(f.get('confirmed_value')),cost_cny:Number(f.get('cost_cny')),duration_hours:Number(f.get('duration_hours')),method:f.get('method')}];const r=await post(base+'/searches/'+study.search_id+'/actions',{actions:proposed});actionPlans.set(study.search_id,proposed);form.querySelector('.action-result').innerHTML='<p>'+esc(r.scope)+'</p><table><thead><tr><th>补证动作</th><th>CNY</th><th>h</th><th>排除已发现反例</th><th>每元条件收益</th></tr></thead><tbody>'+r.actions.map(a=>'<tr><td>'+esc(a.method)+'</td><td>'+num(a.cost_cny)+'</td><td>'+num(a.duration_hours)+'</td><td>'+a.excluded_observed_counterexamples+'</td><td>'+num(a.reduction_per_cny,5)+'</td></tr>').join('')+'</tbody></table><p>已持久化并纳入证书。收益为条件情景；无反例时保持未知。</p>';},e.submitter);};});};
  let previous;
  const refresh=async()=>{const studies=await request(base+'/searches');const snapshot=JSON.stringify(studies);if(host.isConnected&&previous!==snapshot){render(studies);previous=snapshot;}return studies;};
  const poller=createPoller(async()=>{if(!host.isConnected){poller.stop();return;}await refresh();},{interval:4000,onError:()=>{previous=null;if(host.isConnected)host.querySelector('#search-list').textContent='连接中断，搜索结论暂不可核验；正在自动重连。';}});
  await refresh();
  if(!host.isConnected)return;
  poller.start();
  host.querySelector('#search-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);action(async()=>{await post(base+'/searches',{run_ids:catalog.run_ids,budget:Number(f.get('budget')),axes:[{material:f.get('material'),values:String(f.get('values')).split(/[,，]/).map(v=>Number(v.trim())),source:f.get('source'),evidence_id:f.get('evidence_id')||null}]});await refresh();poller.start();},e.submitter);};
}
