import { request, escape as esc } from './api.js';

export async function spatialWorkspace(state, host, action, notice, evidenceDetail) {
  const pid=state.project.project_id, source=state.evidence.filter(e=>['drawing','manual_input'].includes(e.type));
  const current=await request('/projects/'+pid+'/geometry');
  if(!host.isConnected)return;
  host.innerHTML=`<div class="view-heading"><div><h1>图纸与构件证据</h1><p>人工标注 → 确认来源 → 简单几何。当前不做自动图纸识别或 IDF 几何同步。</p></div></div><div class="spatial-split"><form id="geometry-form"><label>来源图纸<select name="evidence_id" required><option value="">选择已导入的图纸</option>${source.map(e=>`<option value="${e.evidence_id}">${esc(e.name)} · ${e.review_state==='confirmed'?'已确认':'待确认'}</option>`).join('')}</select></label><div id="drawing-source"></div><div class="form-grid"><label>层高 m<input name="floor_height_m" type="number" min=".1" max="20" step=".01" required value="${current?.schema.floor_height_m||3}"></label><label>层数<input name="floors" type="number" min="1" max="30" required value="${current?.schema.floors||1}"></label></div><p class="subtle">坐标单位为米。逐段填写边界墙；厚度必须来自图纸或测量，未知构件保留 UNKNOWN。</p><div id="wall-rows"></div><button type="button" id="add-wall">＋ 增加墙体</button><label>复核人<input name="responsible_person" required value="${esc(state.user.display_name)}"></label><label>比例、单位与人工确认依据<textarea name="review_note" required minlength="5" placeholder="例如：按 A-17 标注尺寸，原点取建筑西南角。"></textarea></label><button class="primary" type="submit">保存 Building Schema 并生成几何</button><p id="geometry-result" role="status">${current?esc(current.status)+' · v'+current.revision:''}</p></form><div><div class="spatial-controls"><label>楼层<select id="floor-filter"><option value="all">全部</option></select></label><label class="check-option"><input type="checkbox" id="xray">X-ray</label></div><div id="spatial-canvas" aria-label="可旋转的建筑构件三维视图"></div><div id="component-drawer"><p class="empty">保存几何后，点击墙体查看证据。</p></div></div></div>`;
  let walls=current?.schema.walls.map(w=>({...w}))||[];
  const sourceSelect=host.querySelector('[name=evidence_id]');
  if(walls.length)sourceSelect.value=walls[0].evidence_id;
  const showSource=()=>{const ev=source.find(e=>e.evidence_id===sourceSelect.value);host.querySelector('#drawing-source').innerHTML=ev?`<p>${esc(ev.source_locator)} · ${esc(ev.review_state)}</p><button type="button" id="source-detail">查看与确认来源</button>${ev.source_file?`<a href="/api/projects/${pid}/files/${ev.source_file}" target="_blank" rel="noopener">查看原文件 ↗</a>`:''}`:'';if(ev)host.querySelector('#source-detail').onclick=()=>evidenceDetail(ev);};sourceSelect.onchange=showSource;showSource();
  const paint=()=>{host.querySelector('#wall-rows').innerHTML=walls.map((w,i)=>`<fieldset class="wall-row"><legend>${esc(w.id)}</legend><div class="wall-coordinates">${['x1','z1','x2','z2','thickness_m'].map(k=>`<label>${k==='thickness_m'?'厚度':k}<input type="number" step=".01" required data-i="${i}" data-field="${k}" value="${w[k]}" ${k==='thickness_m'?'min=".01" max="2"':'min="-1000" max="1000"'}></label>`).join('')}</div><label>来源定位<input required data-i="${i}" data-field="source_locator" value="${esc(w.source_locator)}" placeholder="图号 / 页码 / 轴线"></label><select data-i="${i}" data-field="status" aria-label="${esc(w.id)} 证据状态">${['UNKNOWN','AI_SUGGESTED','CONFIRMED'].map(s=>`<option ${s===w.status?'selected':''}>${s}</option>`).join('')}</select><button type="button" data-remove="${i}">移除此草稿构件</button></fieldset>`).join('');host.querySelectorAll('[data-field]').forEach(input=>{input.onchange=()=>{walls[Number(input.dataset.i)][input.dataset.field]=input.type==='number'?Number(input.value):input.value;};});host.querySelectorAll('[data-remove]').forEach(b=>{b.onclick=()=>{walls.splice(Number(b.dataset.remove),1);paint();};});};paint();
  host.querySelector('#add-wall').onclick=()=>{const ids=new Set(walls.map(w=>w.id));let n=1;while(ids.has('W-'+n))n++;walls.push({id:'W-'+n,x1:0,z1:0,x2:0,z2:0,thickness_m:.2,source_locator:'',status:'UNKNOWN',evidence_id:'',insulation:null});paint();};
  let revision=current?.revision||0, dispose=()=>{};
  const render=async data=>{dispose();dispose=await renderScene(data,host,evidenceDetail,state);};
  if(current)await render(current);
  host.querySelector('#geometry-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);action(async()=>{if(!walls.length)throw Error('请先标注至少一段墙体');const data=await request('/projects/'+pid+'/geometry',{method:'PUT',body:JSON.stringify({expected_revision:revision,floor_height_m:Number(f.get('floor_height_m')),floors:Number(f.get('floors')),responsible_person:f.get('responsible_person'),review_note:f.get('review_note'),walls:walls.map(w=>({...w,evidence_id:w.evidence_id||f.get('evidence_id')}))})});revision=data.revision;host.querySelector('#geometry-result').textContent='已保存 v'+revision+' · '+data.status;await render(data);notice('几何已生成；未自动修改 EnergyPlus 模型。');},e.submitter);};
}

async function renderScene(data,host,evidenceDetail,state) {
  const THREE=await import('three'), {OrbitControls}=await import('three/addons/controls/OrbitControls.js');
  if(!host.isConnected)return ()=>{};
  const target=host.querySelector('#spatial-canvas');target.innerHTML='';
  const scene=new THREE.Scene();scene.background=new THREE.Color('#f2f2ee');
  const camera=new THREE.PerspectiveCamera(45,1,.05,10000);
  const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));target.append(renderer.domElement);
  const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;
  scene.add(new THREE.HemisphereLight(0xffffff,0x89908b,2.2));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(20,40,10);scene.add(light);
  const meshes=data.components.map(c=>{const color=data.status==='STALE'?0xbc5545:c.source_status==='ASSUMED'?0xc5a46c:c.status==='CONFIRMED'?0x709786:c.status==='AI_SUGGESTED'?0xc5a46c:0xa7acaa;const mesh=new THREE.Mesh(new THREE.BoxGeometry(...c.size),new THREE.MeshStandardMaterial({color,roughness:.85}));mesh.position.set(...c.center);mesh.rotation.y=c.rotation_y;mesh.userData=c;scene.add(mesh);return mesh;});
  const bounds=new THREE.Box3();meshes.forEach(m=>bounds.expandByObject(m));const size=bounds.getSize(new THREE.Vector3()),center=bounds.getCenter(new THREE.Vector3()),span=Math.max(size.x,size.y,size.z,5);camera.position.copy(center).add(new THREE.Vector3(span,span*.85,span));controls.target.copy(center);
  const grid=new THREE.GridHelper(span*2,20,0xb8c0bb,0xdce0dc);grid.position.set(center.x,-.01,center.z);scene.add(grid);
  const resize=()=>{const width=target.clientWidth;renderer.setSize(width,420);camera.aspect=width/420;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(target);resize();
  host.querySelector('#floor-filter').innerHTML='<option value="all">全部</option>'+Array.from({length:data.schema.floors},(_,i)=>'<option value="'+(i+1)+'">'+(i+1)+' 层</option>').join('');
  host.querySelector('#floor-filter').onchange=e=>{meshes.forEach(m=>{m.visible=e.target.value==='all'||m.userData.floor===Number(e.target.value);});};
  host.querySelector('#xray').onchange=e=>{meshes.forEach(m=>{m.material.transparent=e.target.checked;m.material.opacity=e.target.checked?.28:1;m.material.depthWrite=!e.target.checked;});};
  let down, selected;
  renderer.domElement.onpointerdown=e=>{down=[e.clientX,e.clientY];};
  renderer.domElement.onpointerup=e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=renderer.domElement.getBoundingClientRect();const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(meshes.filter(m=>m.visible))[0];if(!hit)return;if(selected)selected.material.emissive.setHex(0);selected=hit.object;selected.material.emissive.setHex(0x173729);const c=selected.userData;const ev=state.evidence.find(e=>e.evidence_id===c.evidence_id);host.querySelector('#component-drawer').innerHTML=`<h3>${esc(c.component_id)}</h3><dl class="metadata"><dt>厚度</dt><dd>${c.size[2]*1000} mm</dd><dt>来源定位</dt><dd>${esc(c.source_locator)}</dd><dt>证据</dt><dd>${esc(c.evidence_id)}</dd><dt>状态</dt><dd>${data.status==='STALE'?'STALE':esc(c.status)}</dd><dt>来源性质</dt><dd>${esc(c.source_status)}</dd><dt>保温层</dt><dd>${esc(c.insulation||'UNKNOWN')}</dd><dt>仿真映射</dt><dd>未绑定 IDF；不声明影响某个能耗结论</dd></dl>${ev?'<button id="component-evidence">查看来源证据</button>':''}`;if(ev)host.querySelector('#component-evidence').onclick=()=>evidenceDetail(ev);};
  let alive=true;const dispose=()=>{if(!alive)return;alive=false;observer.disconnect();controls.dispose();meshes.forEach(m=>{m.geometry.dispose();m.material.dispose();});grid.geometry.dispose();grid.material.dispose();renderer.dispose();};
  const frame=()=>{if(!alive)return;if(!host.isConnected){dispose();return;}controls.update();renderer.render(scene,camera);requestAnimationFrame(frame);};frame();return dispose;
}
